import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import moment from 'moment';

const Home: NextPage = () => {
  let timer: any = null;
  const [time, setTime] = useState(moment());
  useEffect(() => {
    // eslint-disable-next-line react-hooks/exhaustive-deps
    timer = setInterval(() => {
      setTime(moment());
    }, 1000);
    return () => {
      clearInterval(timer);
    };
  }, []);
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
          <div className="title">
            <h1>Logo</h1>
          </div>
          <div className="time">{time.format('YYYY.MM.DD HH:mm:ss')}</div>
          <div className="util">
            <a
              href="#"
              target="_blank"
            >
              <span>
                <Image
                  src="/images/share_icon.svg"
                  alt="share icon"
                  width={35}
                  height={25}
                />
              </span>
            </a>
            <button className='basic-button'>내정보관리</button>
          </div>
        </header>
        <div className="content">
          <nav>
            <ul>
              <li>
                <button title="Collapse" className="menu-level-button-right">
                  <svg xmlns="http://www.w3.org/2000/svg" width="5" height="7">
                    <path
                      d="M 1 0.5 L 1 5.5 L 4 3 Z"
                      fill="#fff"
                    ></path>
                  </svg>
                </button>
                <Link href={'/'}>
                  <a className={styles.menu}>레벨1메뉴</a>
                </Link>
              </li>
              <li>
                <button title="Collapse" className="menu-level-button-right">
                  <svg xmlns="http://www.w3.org/2000/svg" width="5" height="7">
                    <path
                      d="M 1 0.5 L 1 5.5 L 4 3 Z"
                      fill="#fff"
                    ></path>
                  </svg>
                </button>
                <Link href={'/'}>
                  <a className={styles.menu}>레벨1메뉴</a>
                </Link>
              </li>
            </ul>
          </nav>
          <div className="page">
            <div className="page-header">
              <div className="page-info">
                <div className="breadcrumb">
                  <span className="home-icon"></span>
                  <ul>
                    <li>
                      <Link href={'/'}>
                        <a className={'breadcrumb-menu-1'}>레벨1메뉴 ▶ </a>
                      </Link>
                    </li>
                    <li>
                      <Link href={'/'}>
                        <a className={'breadcrumb-menu-2'}>레벨2메뉴 ▶ </a>
                      </Link>
                    </li>
                  </ul>
                  <h2>페이지 타이틀</h2>
                </div>
                <div className="list-count">
                  <span className="font-orange">0,000</span> 건
                </div>
              </div>
              <div className="page-funtion">
                <button className='basic-button'>기능버튼</button>
              </div>
            </div>
            <div className="page-main">페이지메인</div>
          </div>
          <div className="my-todo">나의할일</div>
        </div>
        <footer className={styles.footer}>
          <a
            href="https://www.deonaeun.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                src="/deonaeun.logo"
                alt="deonaeun logo"
                width={72}
                height={40}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  )
}

export default Home
